# Generated by Django 3.2.8 on 2021-11-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(default='无', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(default='')),
                ('logo', models.CharField(max_length=250)),
                ('population', models.IntegerField(default=1)),
            ],
        ),
    ]
