# Generated by Django 3.2.8 on 2021-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('solved', models.BigIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('content', models.TextField(default='')),
                ('initial_points', models.BigIntegerField(default=0)),
                ('minimum_points', models.BigIntegerField(default=0)),
                ('decay', models.BigIntegerField(default=0)),
                ('flag', models.CharField(default='', max_length=512)),
                ('ChallengeClass', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('points', models.BigIntegerField(default=0)),
            ],
        ),
    ]
